// 4Assigment/swa-4/src/components/LoginComponent.vue
<template>
    <div class="container">
        <h1>Login</h1>
        <div class="content">
            <div class="form">
                <div class="txt_field">
                    <input type="text" v-model="username"/>
                    <span></span>
                    <label>Username</label>
                </div>
                <div class="txt_field">
                    <input type="password" v-model="password"/>
                    <span></span>
                    <label>Password</label>
                </div>
                <button @click="logIn()">Login</button>
            </div>
        </div>
        <RouterLink to="/register">Not a member? Register!</RouterLink>
        <p class="error">{{message}}</p>
</div>
</template>

<script lang="ts">
import * as API from '../API/gameAPI'
import { model } from '../API/store'
import { defineComponent } from "vue";
export default defineComponent({
    data() {
        return {
            model,
            username: '',
            password: '',
            message: ''
        }
    },
    methods: {
        logIn() {
            API.loginUser(this.username, this.password).then((result) => {
                if (result !== 'Invalid username or password') {
                    
                    model.login(result);
                    this.message = '';
                    console.log(result);
                } else {
                    this.message = result;
                }
            });
        }
    },
    
})
</script>

// 3Assigment/my-app/src/components/Login.tsx
import {useState} from "react";
import {Link} from "react-router-dom";
import {login} from "../features/userService";
import {useAppDispatch} from "../app/hooks";
import {loginUser} from "../api/gameAPI";
import {useNavigate} from 'react-router-dom';

export default function Login(){
    const navigate = useNavigate();
    const dispatch = useAppDispatch();

    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");
    const [message, setMessage] = useState("");

    const handleUsernameChange = (event: any) => {
        setUsername(event.target.value);
    }
    const handlePasswordChange = (event: any) => {
        setPassword(event.target.value);
    }

    const logIn = () => {
        loginUser(username, password).then((response) => {
            if(response !== 'Invalid username or password'){
                dispatch(login(response));
                setMessage("")
                navigate("/");
            } else {
                setMessage(response);
            }
        });
    };

    return (
        <div className='login-container'>
        <h1>Login</h1>
        <div className='login-form'>
            <div className='login-form-row'>
                <label htmlFor='username'>Username</label>
                <input type='text' id='username' value={username} onChange={handleUsernameChange}/>
            </div>
            <div className='login-form-row'>
                <label htmlFor='password'>Password</label>
                <input type='password' id='password' value={password} onChange={handlePasswordChange}/>
            </div>
            <div className='login-form-row'>
                <button onClick={logIn}>Login</button>
            </div>
            <div className='login-form-row'>
                <label htmlFor='register'>Don't have an account?</label>
                <button id='register'><Link to='/register'>Register</Link></button>
            </div>
            <div className='login-form-row'>
                <label>{message}</label>
            </div>
        </div>
    </div>
    )
}
