// 3Assigment/my-app/src/components/Board.tsx
import React, {useEffect, useState} from "react";

import { Generator } from '../model/board'
import * as BoardModel from '../model/board'
import { useAppSelector, useAppDispatch } from '../app/hooks';
import { RootState } from '../app/store';
import {
    setSelectedPiece,
    setMessage,
    setMatches,
    clearMatches,
    setCalculatingMove,
} from '../features/playService';
import {
    setGame,
    setBoard,
    increaseScore,
    decreaseMoves,
    endGame,
    Game, startGame
} from '../features/gameService'
import './Board.css';
import { getAllGames, getGameById, startNewGame, updateGame } from '../api/gameAPI';


export class RandomGenerator implements Generator<string> {
    private values : string[];
    private min: number;
    private max: number;
    constructor(values:string){
        this.values = values.split(",");
        this.min = 0;
        this.max = this.values.length - 1;
    }
    next(): string {
        const index = Math.floor(Math.random() * (this.max - this.min + 1)) + this.min;
        return this.values[index];
    }
}
type ElementProps = {
    value: string;
    rowIndex : number;
    columnIndex : number;
}

export function RowElement ({rowIndex, columnIndex, value}:ElementProps) {
    const dispatch = useAppDispatch();
    const firstSelectedPiece : BoardModel.Position | undefined = useAppSelector((state:RootState) => state.play.selectedPiece);
    const game : Game = useAppSelector((state:RootState) => state.game);
    const matches : BoardModel.Position[] = useAppSelector((state:RootState) => state.play.matches);
    const calculatingMove : boolean = useAppSelector((state:RootState) => state.play.calculatingMove);
    const generator : Generator<string> = new RandomGenerator('♥,♦,♣,♠');
    const [selected, setSelected] = useState<boolean>(false);

    useEffect(() => {
        if(!firstSelectedPiece){
            setSelected(false);
        }
    }, [firstSelectedPiece, setSelected])
    function timeout(ms: number) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    const selectedElement = async () => {
        if (!calculatingMove && !game.completed){
            setSelected(true);
            if(firstSelectedPiece){
                dispatch(setCalculatingMove(true));
                const moveResults : BoardModel.MoveResult<string> = BoardModel.move(generator, {...game.board}, firstSelectedPiece, {row: rowIndex, col: columnIndex});
                if(moveResults.effects.length > 0){
                    dispatch(decreaseMoves())
                    const nBoard : BoardModel.Board<string> = JSON.parse(JSON.stringify(game.board)) as typeof game.board;
                    nBoard.pieces[firstSelectedPiece.row][firstSelectedPiece.col] = BoardModel.piece(nBoard, {row: rowIndex, col : columnIndex});
                    nBoard.pieces[rowIndex][columnIndex] = BoardModel.piece(game.board, firstSelectedPiece);
                    dispatch(setBoard(nBoard));
                    dispatch(setSelectedPiece(undefined));
                    setSelected(false);
                    for (let effect of moveResults.effects){
                        if(effect.kind === "Match"){
                            dispatch(increaseScore((effect.match.positions.length -2) *5));
                            dispatch(setMatches( effect.match.positions));
                        }else{
                            dispatch(setMessage("Refilling"));
                            await timeout(1000);
                            dispatch(setBoard(effect.board))
                            dispatch(setMessage(""));
                            dispatch(clearMatches());
                        }
                    }
                    await timeout(1000);
            }else{
                dispatch(setMessage("Invalid Move"));
                setTimeout(() => {
                    dispatch(setMessage(""));
                }, 1000);
            }
            dispatch(setSelectedPiece(undefined));
            setSelected(false);
            dispatch(setCalculatingMove(false));
        }else{
            dispatch(setSelectedPiece({row: rowIndex, col: columnIndex}));
        }
    }
}
    return (
        <>
        <button className={(selected || (matches.some(pos => pos.row === rowIndex && pos.col === columnIndex))) ? 'row-element row-element--selected' : 'row-element'} onClick ={() => selectedElement()}>{value}</button>
        </>
    );
}
type rowProps = {
    rowIndex : number;
    row : string[];
}
export function Row ({rowIndex, row}:rowProps) {
    return (
        <div>{row.map((value, columnIndex) => <RowElement key={'element' + rowIndex + columnIndex} rowIndex={rowIndex} columnIndex={columnIndex} value={value}/>)}</div>
    );
}

export default function Board() {
    const token = useAppSelector((state:RootState) => state.user.token);
    const game : Game = useAppSelector((state:RootState) => state.game);
    const message : string = useAppSelector((state:RootState) => state.play.message);
    const [playStarted, setPlayStarted] = useState<boolean>(false);
    const dispatch = useAppDispatch();
    const [games, setGames] = useState<Game[]>([]);
    const continueGame = (id : number) => {
        setPlayStarted(true);
        getGameById(token, id).then((game) => { dispatch(setGame(game))});
    }
    const startNew = () => {
        setPlayStarted(true);
        dispatch(startGame());
        startNewGame(token).then((game) => { dispatch(setGame(game))});
    }
    useEffect(() => {
        if(!playStarted){
            getAllGames(token).then((games) => { setGames(games)});
        }
    }, [playStarted]);
    useEffect(() => {
        if(playStarted){
            if(game.score >= game.targetScore || (game.nrOfMoves === 0 && game.score < game.targetScore)) {
                dispatch(endGame());
                updateGame(token, game.id, { ...game,completed: true})
            }else{
                updateGame(token, game.id, game);
            }
        }
    }, [game.board]);

    return (
       <>
        {playStarted ? (
            <>
            {!game.completed ? (
                <div className="info">    
                 <div className='target-score'>
                                TARGET SCORE: {game.targetScore}
                            </div>
                            <div className='score'>
                                YOUR SCORE: {game.score}
                            </div>
                            <div className='moves'>
                                MOVES LEFT: {game.nrOfMoves}
                            </div>
                        </div>
            ) : (
                <div className='play-end'>
                            GAME OVER!
                            <div>
                                <button onClick={() => setPlayStarted(false)}>Back to main page</button>
                            </div>
                        </div>
                    )}
                    <div className='board'>
                        {game.board ? game.board.pieces ? game.board.pieces.map((row, rowIndex) => <Row key={'row' + rowIndex} rowIndex={rowIndex} row={row} />) : null : null}
                    </div>
                    <div className='message'>
                        {message}
                    </div>
                    </>
                ) : (
                    <div>
                    {games.filter((game) => !game.completed).map((game) => (
                        <button key={game.id} onClick={() => continueGame(game.id)}>Game {game.id}</button>
                    ))}
                    <div>
                        <button onClick={() => startNew()}>New Game</button>
                    </div>
                </div>
        )}
       </>
    );
}

// 4Assigment/swa-4/src/components/BoardComponent.vue
<template>
    <div>
        <div class="center" v-if="playStarted">
            <div>
                <button class='btn btn-warning' v-if="!model.gamePlay.calculatingMove" @click="backToMain()">Back to main
                    page</button>
            </div>
            <div class='play-info' v-if="!model.game.completed">
                <div class='play-target-score'>
                    TARGET SCORE: {{ model.game.targetScore }}
                </div>
                <div class='play-score'>
                    YOUR SCORE: {{ model.game.score }}
                </div>
                <div class='play-moves'>
                    MOVES LEFT: {{ model.game.nrOfMoves }}
                </div>
            </div>
            <div class='play-end' v-else>
                <div v-if="model.game.score >= model.game.targetScore">Congrats! You won with a score of {{
                        model.game.score
                }} and {{ model.game.nrOfMoves }} moves left.</div>
                <div v-else>You were {{ (model.game.targetScore - model.game.score) }} points away! Try again?</div>
            </div>
            
            <div class='row' v-for="(row, index) in model.game.board?.pieces" v-bind:key="'Row' + index">
                <div class='element' v-for="(element, colIndex) in row" v-bind:key="'Tile' + index + ',' + colIndex">
                    <BoardElement :rowIndex='index' :colIndex='colIndex' :element='element' />
                </div>
            </div>
            <div class='play-message'>
                {{ model.gamePlay.message }}
            </div>
        </div>
        <div class="center" v-else>
            <h2>Continue your games:</h2>
            <div class='container'>
                <div class='row'>
                    <button class='btn btn-light btn-block col-4'
                        v-for="game in model.games.filter((game) => !game.completed && game.user === model.user.userId)"
                        v-bind:key="game.id" @click="continueGame(game.id)">Game {{ game.id }}</button>
                </div>
            </div>
            <div>
                <h2 class='mt-3'>Start a new game:</h2>
                <button class='btn btn-info' @click="startAnotherGame()">New Game</button>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import * as API from '../API/gameAPI'
import { model } from '../API/store'
import BoardElement from './BoardElement.vue'
import { defineComponent } from "vue";

export default defineComponent({
    data() {
        return {
            model,
            playStarted: false,
        }
    },
    methods: {
        backToMain() {
            this.playStarted = false;
        },
        continueGame(id: number) {
            this.playStarted = false;
            model.emptyGame();
            let hasBoard = true;
            API.getGameById(model.user.token!, id)
                .then((result) => { model.setGame(result), result.board ? hasBoard = true : hasBoard = false })
                .then(() => {
                    if (!hasBoard) {
                        model.initNewGame();
                        API.updateGame(model.user.token!, model.game.id, model.game);
                    }
                })
                .then(() => this.playStarted = true);
        },
        startAnotherGame() {
            this.playStarted = false;
            model.emptyGame();
            model.initNewGame();
            API.startNewGame(this.model.user.token!)
                .then((result) => {
                    API.updateGame(model.user.token!, result.id, {
                        ...this.model.game, id: result.id, user: model.user.userId!
                    }),
                        model.setGame({ ...model.game, id: result.id })
                })
                .then(() => this.playStarted = true);
        }
    },
    mounted() {
        const findGames = async () => {
            API.getAllGames(model.user.token!).then((result) => {
                model.games = result!
            })
            setTimeout(findGames, 5000)
        }

        findGames()
    },
    components: {
        BoardElement
    },
})
</script>


<style>
/* .play-message {
    position: absolute;
    bottom: 0;
    margin-bottom: 20px;
} */

.element {
    width: 50px !important;
    padding: 0 !important;
    margin-top: 0 !important;
}

.row {
    margin-left: 5px !important;
    display: flex;
    justify-content: center;
}
.center {
    text-align: center;
}
</style>
