// 3Assigment/my-app/src/components/Register.tsx
import {Link, useNavigate} from "react-router-dom";
import {useState} from "react";
import {registerUser} from "../api/gameAPI";

export default function Register(){
    const navigate = useNavigate();

    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");
    
    const [message, setMessage] = useState("");

    const register = () => {
            registerUser(username, password).then((response) => {
                if (response !== 'Username already taken') {
                    setMessage("")
                    navigate('/');
                } else {
                    setMessage(response);
                }
            });
    };

    const handleUsernameChange = event => {
        setUsername(event.target.value);
    };

    const handlePasswordChange = event => {
        setPassword(event.target.value);
    };


    return (
        <div className='register-container'>
            <h1>Register</h1>
            <div className='register-form'>
                <div className='register-form-row'>
                    <label htmlFor='username'>Username</label>
                    <input type='text' id='username' value={username} onChange={handleUsernameChange}/>
                </div>
                <div className='register-form-row'>
                    <label htmlFor='password'>Password</label>
                    <input type='password' id='password' value={password} onChange={handlePasswordChange}/>
                </div>
                <div className='register-form-row'>
                    <button onClick={register}>Register</button>
                </div>
                <div className='register-form-row'>
                    <label htmlFor='login'>Already have an account?</label>
                    <button id='login'><Link to='/login'>Login</Link></button>
                </div>
                <div className='register-form-row'>
                    <label htmlFor='message'>{message}</label>
                </div>
            </div>
        </div>
    )
}

// 4Assigment/swa-4/src/components/RegisterComponent.vue
<template>
    <div class="container">
        <h1>Register</h1>
        <div class="content">
            <div class="form">
                <div class="txt_field">
                    <input type="text" v-model="username"/>
                    <span></span>
                    <label>Username</label>
                </div>
                <div class="txt_field">
                    <input type="password" v-model="password"/>
                    <span></span>
                    <label>Password</label>
                </div>
                <div class="txt_field">
                    <input type="password" v-model="password2"/>
                    <span></span>
                    <label>Repeat Password</label>
                </div>
                <button @click="register()">Login</button>
            </div>
            <p class="error">{{message}}</p>
        </div>
        
</div>
</template>
<script lang="ts">
import * as API from '../API/gameAPI'
import { model } from '../API/store'
import { defineComponent } from "vue";

export default defineComponent({
    data() {
        return {
            model,
            username: '',
            password: '',
            password2: '',
            message: ''
        }
    },
    methods: {
        register() {
            if (this.password == this.password2) {
                API.registerUser(this.username, this.password).then((result) => {
                    if (result !== 'Username already taken') {
                        this.message = '';
                    } else {
                        this.message = result;
                    }
                });
            } else {
                this.message = 'Passwords do not match';
            }
        }
    }
})
</script>
